version: "3.0"

services:
  selenium:
    container_name: selenium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    shm_size: "2gb"
  api:
    container_name: "api"
    build:
      context: ./api
    volumes:
      - ./api:/api
    ports:
      - "8080:8080"
    depends_on:
      - selenium
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    working_dir: /frontend
    command: [ "npm", "run", "dev" ]
